# Generated by Django 4.0.2 on 2022-02-18 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petdetails',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
